version: "3.3"

services:
  nginx:
    image: nginx:1.17.2
    ports:
      - "81:80"
    links:
      - php
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
  php:
    volumes:
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3380:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - datavolume:/var/lib/mysql
volumes:
  datavolume:
  vendors:
